I will start with the installation page of the github for the Starfish suite of tools. (https://github.com/egluckthaler/starfish/wiki/Installation) 

For installation, I will try the apptainer option, since that is what we have been working with the most in the class:
```
apptainer pull starfish.sif oras://ghcr.io/egluckthaler/starfish:latest
```


 First, I will set up some folders under Final_Project to try to start out organized.
 I will use /software, /software/containers, /data, /scripts, /documentation
 

 Now I will cd into software/containers and try to pull the apptainer image there. 

It appears to be working, but it does say that it will take 1 hour. I will let it run and check back later.

It seems to have worked. I will set up a github repository for this project and try to test the apptainer's installation.

Unfortunately, I started my github repository while my pwd was final_project/software/containers. 
When I then tried to start back up at /final_project, two levels up, I got errors about nested repositories.
I consulted DeepSeek AI to remedy this situation. Its recommendations:

```
# Step 1: Verify the nested repo exists:
# From your project root
cd /fs/ess/PAS2880/users/kstarr791/final_project

# Check for multiple .git directories
find . -name ".git" -type d

# You should see at least two: ./.git and ./software/containers/.git
```
True, I do see both.

```
# Step 2: Remove the nested .git directory:

# Remove the accidental git repository
rm -rf software/containers/.git

# Verify it's gone
find . -name ".git" -type d
# Should now only show: ./.git
```

Also true, that is what I see. 

The recommendation from DeepSeek for testing the apptainer is this:
```
# Test if the container is valid and can run
apptainer exec starfish.sif echo "Hello from Starfish container!"
```

The output:

```
[kstarr791@p0219 final_project]$ cd software/containers/
[kstarr791@p0219 containers]$ apptainer exec starfish.sif echo "Hello from Starfish container!"
INFO:    gocryptfs not found, will not be able to use gocryptfs
source: /opt/conda/envs/starfish/etc/conda/activate.d/activate-binutils_linux-64.sh:10:40: parameter expansion requires a literal
source: /opt/conda/envs/starfish/etc/conda/activate.d/activate-gcc_linux-64.sh:10:40: parameter expansion requires a literal
source: /opt/conda/envs/starfish/etc/conda/activate.d/activate-gxx_linux-64.sh:10:40: parameter expansion requires a literal
Hello from Starfish container!
```

So far so good, I think!

I also received a recommendation from DeepSeek regarding organization and set up, to make a script that sets up the environment.
I think this is a smart choice, as it seems that it will simplify some things later. Some of the recommendations are new to me, so I made sure to learn a bit more about them. 

Here is the script:

```
#!/bin/bash
# /fs/ess/PAS2880/users/kstarr791/final_project/project_env.sh

# Base directory
export PROJECT_DIR="/fs/ess/PAS2880/users/kstarr791/final_project"

# Container location (after your 1-hour download completes)
export STARFISH_CONTAINER="$PROJECT_DIR/software/containers/starfish.sif"

# Data directories
export RAW_DATA="$PROJECT_DIR/data/raw"
export PROCESSED_DATA="$PROJECT_DIR/data/processed"
export RESULTS="$PROJECT_DIR/data/results"

# Add your scripts to PATH so you can run them from anywhere
export PATH="$PROJECT_DIR/scripts:$PATH"

# Create a shortcut command for running starfish tools
alias starfish_run="apptainer exec $STARFISH_CONTAINER"
```

I'm familiar from this course with setting variables to avoid typing long file paths repeatedly, and for ease of reproducibility.
However, the export and alias functions are new to me. The export command seems to make the contents of this project more accessible and easy to move later.
This might be useful to me if I choose to move this to another project in the future for further analyses if I get Starfish working. 

I also think this might be useful, since the Starfish software seems to use conda, which I know operates on "environments" as well, so I'm wondering if this might help everything work together smoothly.